Add cli_options to .pronto_stylelint.yml
kevinjalbert/pronto-stylelint pull request #1
Opened 2017-02-15 22:40 UTC by aergonaut

Allows passing of more CLI options to the stylelint command when running
in Pronto. This allows specifying a custom .stylelintrc file, for
example.

cli_options always appends -f json so the format should always be JSON.

I wanted to add this because my team would like to use pronto-stylelint but it would give us some more flexibility to store our .stylelintrc file outside of our repo, so being able to specify the --config flag would help us.

2017-02-28 12:50 UTC, kevinjalbert requested changes
Sorry for the delay in looking at this.

@aergonaut this looks great and should help others out. I'm curious if you can add a simple spec just to to exercises the new feature you've added?

2017-02-28 17:26 UTC, aergonaut commented
Yes definitely

2017-04-25 03:21 UTC, kevinjalbert approved these changes

2017-04-25 03:24 UTC, kevinjalbert commented
@aergonaut I've jumped on your branch and added the tests (in addition to some other refactoring goodies!).

I appreciate the PR and the initial work you've put into this. Thank you for pushing this project forward even more. I'll be merging this PR right now 😄

2017-04-25 03:25 UTC, merged