Use Pronto YML For Config
kevinjalbert/pronto-stylelint pull request #15
Opened 2024-06-25 14:13 UTC by Phillita

# Motivation

To reduce the number of config files needed for pronto integrations. Pronto has a config that can handle plugin config.

# Changes

- Added a new config class to handle all config for the gem
- Deprecated use of the old config file
    - It still works but a warning will be issued
- Handled a bunch of Rubocop warnings

2024-07-01 03:23 UTC, kevinjalbert requested changes
👋🏻 It has been a while since I've done anything with this repo, or even using pronto 😅.

What you are proposing here makes sense though, remove the bespoke config as Pronto has better support for configs of plugins.

---

I'm thinking it would better to just make a breaking change and adopt the pronto config approach.

**Request changes:**
  - **I noticed that tests are emitting the deprecation warning you put in. We would simplify config logic (to the new approach) and just remove the old way.**
  - **Update the README to reflect the new config approach (link to official pronto docs for an example)**
  
🙇🏻 Much appreciated on your contributions, looking forward to the changes.

---

Also, just notes to me.

It took me a bit to 'run the tests' of this PR, was hitting some node issue with `stylelint` (and the `meow` package), had to go to the latest node version. Could have a better 'how to test/contribute' in the README.

The CI for this repo doesn't work anymore and probably should just be a GitHub Action now.

2024-07-04 19:13 UTC, Phillita commented
> 👋🏻 It has been a while since I've done anything with this repo, or even using pronto 😅.
> 
> What you are proposing here makes sense though, remove the bespoke config as Pronto has better support for configs of plugins.
> 
> I'm thinking it would better to just make a breaking change and adopt the pronto config approach.
> 
> **Request changes:**
> 
> * **I noticed that tests are emitting the deprecation warning you put in. We would simplify config logic (to the new approach) and just remove the old way.**
> * **Update the README to reflect the new config approach (link to official pronto docs for an example)**
> 
> 🙇🏻 Much appreciated on your contributions, looking forward to the changes.
> 
> Also, just notes to me.
> 
> It took me a bit to 'run the tests' of this PR, was hitting some node issue with `stylelint` (and the `meow` package), had to go to the latest node version. Could have a better 'how to test/contribute' in the README.
> 
> The CI for this repo doesn't work anymore and probably should just be a GitHub Action now.

Thank you for replying! This is one of many pull requests I've recently submitted to upgrade Pronto plugins. I just wanted to let you know you're the first to reply.
I'll get your changes introduced as soon as I can. Also, thank you for the original gem code!

2024-08-02 18:13 UTC, Phillita commented
@kevinjalbert Sorry about the delay. I was away on vacation and had been unplugged. I've made the changes as you requested!

2025-01-20 02:26 UTC, merged

2025-01-20 02:37 UTC, kevinjalbert commented
Got it all merged in, and a new version released (https://rubygems.org/gems/pronto-stylelint/versions/0.11.0).

🙇🏻 thank you again, and sorry for the large delay.

2025-01-20 16:02 UTC, Phillita commented
> Got it all merged in, and a new version released (https://rubygems.org/gems/pronto-stylelint/versions/0.11.0).
> 
> 🙇🏻 thank you again, and sorry for the large delay.

Amazing! Thank you for making these changes!