Add files_to_lint to .pronto_stylelint.yml
kevinjalbert/pronto-stylelint pull request #5
Opened 2017-10-16 14:48 UTC by zhuravel

Stylelint hasn't been working well with SASS files for me (there is no working Sass syntax parser for PostCSS), that’s why I would like to have `files_to_lint` option configurable to only lint *.scss files.

This option is configurable in `pronto-eslint_npm` gem and that is very helpful.

Example .pronto_stylelint.yml:
``` yaml
stylelint_executable: './node_modules/.bin/stylelint'
files_to_lint: '\.(c|sc)ss$'

2017-10-17 03:09 UTC, kevinjalbert requested changes
Looks great!

I just ask that:
  1. You update the README with the new option you are proposing
  2. Add some basic specs that test the new changes (i.e., add a [new context to the spec](https://github.com/kevinjalbert/pronto-stylelint/blob/967060151a2c76ebf946663c94fc85c6f79aa6f0/spec/pronto/stylelint_spec.rb#L151-L169) for when you have a custom regex for files.

2017-10-17 10:12 UTC, zhuravel commented
@kevinjalbert Updated 👌

2017-10-18 02:52 UTC, kevinjalbert commented on spec/pronto/stylelint_spec.rb
> +            add_to_index('style.scss', <<-HEREDOC)
TIL you can close the method call and still have the `HEREDOC` afterwards.

2017-10-18 02:54 UTC, kevinjalbert approved these changes
Looks great 👍

Will merge this in and drop a gem update.

2017-10-18 02:56 UTC, merged